# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df9dfe1246b10f2c95cc0eaa889af21b728abbce83db66401ce7d07b44ba27c9a8f0f231a01089c33b4563d70b219a0ab77e1d1ba0aa3c499c586ccd0e45e93

test:
  secret_key_base: 405d5cfe58bf409adbe7ea3da846212dba4a9537f7d5eb7aee48a6a88def5ca694b9512e5996d273064da1bb01121a91d183c49d54cca3ed457bb212a8160a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
